<?php
error_reporting(E_ERROR  | E_PARSE);
require_once("lib.php"); 

	/**
* Generated by Smart Report Maker
*All copyrights are preserved to StarSoft
*http://mysqlreports.com/
*
*/
	

	if(isset($_GET['start'])) {$start = $_GET['start'];} else { $start=0;}

	if(isset($_GET['print'])) {$print = $_GET['print'];}
          else
	{$print=0;}

   	$link_home = $_SERVER["PHP_SELF"];	

	

	//*************************create sql statement  *******************

	if($datasource=='sql')

	{

		$sql = Prepare_QSql();

	}

	else

	{

		$sql = Prepare_TSql();	



	}

	//get number of rows

	$result = query($sql,"LayOut : Prepare SQL" );

	$nRecords = mysql_num_rows($result); //$$$
	

	/* ***********begin of export section*********** */

	if(isset($_GET['export']))

    {

      $export = $_GET['export'];

    }

    else

    {

       $export = "";

    }

	//export data

	if($export =='csv' )

	{

		export_csv($sql,false,0,10);

		exit;

	}

	elseif($export == 'csv1')

    {

       export_csv($sql,true,$start,$records_per_page);

       exit;

    }

	else if($export=='xml')

	{

		export_xml($sql,false,0,10);

		exit;

	}

	elseif($export == 'xml1')

    {

        export_xml($sql,true,$start,$records_per_page);

		exit;

    }

	else if($export =='pdf1')

	{

		if(count($fields)>8)

     		get_pdf($sql,'a4','landscape',10,10,10,10,780,800,10,11,true,$start,$records_per_page);

     	else

      		get_pdf($sql,'a4','portrait',10,10,10,10,490,500,9,10,true,$start,$records_per_page);

	  exit;

	}

	else if($export =='pdf')

    {

     	if(count($fields)>8)

     		get_pdf($sql,'a4','landscape',10,10,10,10,780,800,10,11,false,$start,$records_per_page);

     	else

     		get_pdf($sql,'a4','portrait',10,10,10,10,490,500,9,10,false,$start,$records_per_page);

	 	exit;

    }

	

    //exporting links

	//current

    $link_pdf_current = $_SERVER["PHP_SELF"]."?export=pdf1&&start=$start";

   	$link_csv_current = $_SERVER["PHP_SELF"]."?export=csv1&&start=$start";

   	$link_xml_current = $_SERVER["PHP_SELF"]."?export=xml1&&start=$start";

	//all

    $link_csv_all = $_SERVER["PHP_SELF"]."?export=csv";

    $link_xml_all = $_SERVER["PHP_SELF"]."?export=xml";

    $link_pdf_all = $_SERVER["PHP_SELF"]."?export=pdf";

	// ********************************************/

	//**************************print links******************************

	$link_print1 = $_SERVER["PHP_SELF"]."?print=1&&start=$start";

	$link_print2 = $_SERVER["PHP_SELF"]."?print=2";

	$link_print_real = $_SERVER['PHP_SELF']."?print=3&start=$start";

	

   //*************************next and prev links *********************

   $next_start =  $start+$records_per_page;

   if($next_start >= $nRecords) $next_start = $start;

   $link_next=$_SERVER["PHP_SELF"]."?start=$next_start ";

   $prev_start = $start - $records_per_page;

   if($prev_start < 0)   $prev_start = 0;

   $link_prev=$_SERVER["PHP_SELF"]."?start=$prev_start";	

	

	//initiaize vars

	$cur_row = 0;

	$toggle_row = 0;

	

	//create new sql includes the start and end limits except in case print all

	if($print !=2)

		$sql .= " limit $start,$records_per_page";	

	$result = query($sql,"Layout: pager");	



	$cur_group_ar=array();  // the current group 

	$last_group_ar = array();   //the newest grou by fields

	$actual_fields = array_diff($fields, $group_by);   //actual columns which will be shown without group by fields
	$actual_columns_count = count($actual_fields);     //number of columns to be shown		

	$group_by_count = count($group_by);

	



?>



 <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<html>

<head>

<script  type="text/javascript"  src="../../Js/jquery-1.6.3.min.js"  ></script>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />

<title><?php  echo $title ?></title>



<link href="<?php 

 if($print!= 0)

 {

	echo "print.css" ;

 }

 else

 {

	echo $style_name . ".css" ;

 }

?>" rel="stylesheet" type="text/css" />

</head>



<body class="MainPage">
<?php include 'menu.php'; ?>
<table border="0"

<?php

//width of report

 if($print != 0)

  echo "width='500'";

 else

  echo "width ='100%'";

?>



 align="center" cellpadding="2" cellspacing="0" class="MainTable" >

  
        
  <!-- ******************** start custom header ******************** !-->

  <?php

  if(!empty($header))

  {

    ?>

  <tr>

    <td colspan="<?php echo $actual_columns_count?>"  valign="top" ><?php echo($header);?></td>

  </tr>

  <tr>

    <td colspan="<?php echo $actual_columns_count?>"  valign="top" class="Separator" ></td>

  </tr>

 <?php

  }

  ?>

  <!-- ******************** end custom header ******************** !-->

<?php if(trim($title) != ''){ ?>
  <tr>

    <td <?php echo($span);?>  valign="top" class="Title" ><?php  echo($title);?></td>

  </tr>
<?php } ?>

  <tr>

    <td class="Separator" colspan="<?echo $actual_columns_count?>"></td>

  </tr>

  <?php 

	//echo var_dump($labels);	

if(mysql_num_rows($result) == 0)
    echo "<tr><td style=\"text-align: left;padding-left: 39px;\" $span class='MainGroup'>No Data Found</td></tr>";		


		while($row = mysql_fetch_array($result,MYSQL_ASSOC))

		{

			//fill array with current grouping fields
			foreach($group_by as $key=>$val)

			{
				$cur_group_ar[$val] = $row[$val] ;

			}					

			

			//print group by fields in case of grouping values variation
			if(count($last_group_ar)!=0)

			{

				$diff_index = grouping_diff_index($cur_group_ar,$last_group_ar);

			}

			else

			{

				$diff_index = 0 ;

			}



			if($diff_index !=-1)

			{

				for($i=$diff_index;$i<count($group_by_source);$i++) 

				{

					if($i ==0 && $diff_index==0)

						echo "<tr><td class='MainGroup'  colspan=". $actual_columns_count ." >" .$labels[$group_by_source[$i]] .": " . $row[$group_by[$i] ] . " </td></tr>";

					else

						echo "<tr><td class='SubGroup'  colspan=". $actual_columns_count ." >" .$labels[$group_by_source[$i]] .": " . $row[$group_by[$i] ] . "</td></tr>";

				}

				

	     //echo"<tr><td height='15' $span class='TableHeader'></td></tr>";



				

		if($cur_row==0)		

		{

?>



  <tr>

    <td>
        
        <table

    <?php

//width of report

 if($print != 0)

  echo "width='500'";

 else

  echo "width ='100%'";

?>



     border="0" cellspacing="0" cellpadding="2" align='center'>

	   <?php }

	 } ?> 



<?php 

			//print table columns

			if( ($group_by_count>0 && $diff_index !=-1) || $cur_row==0  ) //if there is a change in grouping

			{

				$i = 0;
                                        //echo var_dump(array_values($actual_fields_source));
                                        //echo var_dump(array_values($actual_fields));
				foreach($actual_fields_source as $key=>$val)

				{
                                           $temp = explode('.', $val);
                                    $field_ = (count($table) == 0)?$val:$temp[1];
                                        if(in_array($field_, $group_by))
                                             continue;
					if($i==0) echo "<tr>";

					echo "<td align='center' class='ColumnHeader'>$labels[$val]</td>";

					if($i == $actual_columns_count -1)  echo "</tr>";

					$i++;

				}

			}



			

			//print row data

			echo "<tr>";

			foreach($actual_fields as $key=>$val)

			{
					if($toggle_row == 0)

						if(empty($row[$val]))

		        			echo "<td align='center' class='TableCell'>" . "&nbsp;" . "</td>";

						else

	        				echo "<td align='center' class='TableCell'>" . $row[$val] . "</td>";

					else

						if(empty($row[$val]))					

							echo "<td align='center' class='AlternateTableCell'>" . "&nbsp;"  ."</td>";					

						else

							echo "<td align='center' class='AlternateTableCell'>" . $row[$val] ."</td>";											

			}

			echo "</tr>";

			

			//change toggling of rows

		  	if($toggle_row == 0)

				$toggle_row = 1;

			else

				$toggle_row =0;

				

			//update new grouping

			if($diff_index !=-1)

			{

				$last_group_ar  =array();

				foreach($group_by as $key=>$val)

				{

					$last_group_ar[$val] = $row[$val] ;

				}

			}

			

			//increment current rows

			$cur_row ++;

		}

?>



    </table>
    
    </td>

  </tr>

  <!-- ******************** start custom footer ******************** !-->

  <?php

  if(!empty($footer))

  {

  echo "<tr><td > $footer</td></tr>";

  }

  ?>

  <!-- ******************** end custom footer ******************** !-->

  <tr>

    <td class="TableFooter">&nbsp;</td>

  </tr>

</table>

 <!-- ************************* Show print Dialog **************************** !-->

<?php 

//show print dialog in case of print mode $$$

if($print==3)

{

	?>

	<script>

 		window.print();

	</script>

	<?php 

}

?>

 <!-- ************************* End Of Show print Dialog ********************* !-->

<script>
 $(document).ready(function(){
 var datasource = <?php echo "'" . $datasource . "';" ; ?>
 if(datasource=='sql'){
 $("#txtordnary_search").css('visibility','hidden');
  $(".srch-btn").css('visibility','hidden');
  $("#search_advanced").css('visibility','hidden');
 
  }
  
 
 });
 
 
 </script>




</body>

</html>

