<?php
error_reporting(E_ERROR  | E_PARSE);
require_once("lib.php"); 

	/**
* Generated by Smart Report Maker
*All copyrights are preserved to StarSoft
*http://mysqlreports.com/
*
*/
          include_once 'Mobile_Detect.php';
          $detect = new Mobile_Detect();
          
	if(isset($_GET['start'])) {$start = $_GET['start'];} else { $start=0;}

	if(isset($_GET['print'])) {$print = $_GET['print'];} else

	$print=0;

   	$link_home = $_SERVER["PHP_SELF"];	

	

	//*************************create sql statement  *******************

	if($datasource=='sql')

	{

		$sql = Prepare_QSql();

	}

	else

	{

		$sql = Prepare_TSql();	



	}

	//get number of rows

	$result = query($sql);

	$nRecords = mysql_num_rows($result); //$$$
	

	/* ***********begin of export section*********** */

	if(isset($_GET['export']))

    {

      $export = $_GET['export'];

    }

    else

    {

       $export = "";

    }

	//export data

	if($export =='csv' )

	{

		export_csv($sql,false,0,10);

		exit;

	}

	elseif($export == 'csv1')

    {

       export_csv($sql,true,$start,$records_per_page);

       exit;

    }

	else if($export=='xml')

	{

		export_xml($sql,false,0,10);

		exit;

	}

	elseif($export == 'xml1')

    {

        export_xml($sql,true,$start,$records_per_page);

		exit;

    }

	else if($export =='pdf1')

	{

		if(count($fields)>8)

     		get_pdf($sql,'a4','landscape',10,10,10,10,780,800,10,11,true,$start,$records_per_page);

     	else

      		get_pdf($sql,'a4','portrait',10,10,10,10,490,500,9,10,true,$start,$records_per_page);

	  exit;

	}

	else if($export =='pdf')

    {

     	if(count($fields)>8)

     		get_pdf($sql,'a4','landscape',10,10,10,10,780,800,10,11,false,$start,$records_per_page);

     	else

     		get_pdf($sql,'a4','portrait',10,10,10,10,490,500,9,10,false,$start,$records_per_page);

	 	exit;

    }

	

    //exporting links

	//current

    $link_pdf_current = $_SERVER["PHP_SELF"]."?export=pdf1&&start=$start";

   	$link_csv_current = $_SERVER["PHP_SELF"]."?export=csv1&&start=$start";

   	$link_xml_current = $_SERVER["PHP_SELF"]."?export=xml1&&start=$start";

	//all

    $link_csv_all = $_SERVER["PHP_SELF"]."?export=csv";

    $link_xml_all = $_SERVER["PHP_SELF"]."?export=xml";

    $link_pdf_all = $_SERVER["PHP_SELF"]."?export=pdf";

	// ********************************************/

	//**************************print links******************************

	$link_print1 = $_SERVER["PHP_SELF"]."?print=1&&start=$start";

	$link_print2 = $_SERVER["PHP_SELF"]."?print=2";

	$link_print_real = $_SERVER['PHP_SELF']."?print=3&start=$start";

	

   //*************************next and prev links *********************

   $next_start =  $start+$records_per_page;

   if($next_start >= $nRecords) $next_start = $start;

   $link_next=$_SERVER["PHP_SELF"]."?start=$next_start ";

   $prev_start = $start - $records_per_page;

   if($prev_start < 0)   $prev_start = 0;

   $link_prev=$_SERVER["PHP_SELF"]."?start=$prev_start";	

	

	//initiaize vars

	$cur_row = 0;

	$toggle_row = 0;

	

	//create new sql includes the start and end limits except in case print all

	if($print !=2)

		$sql .= " limit $start,$records_per_page";	

	$result = query($sql);	



	$cur_group_ar=array();  // the current group 

	$last_group_ar = array();   //the newest grou by fields

	$actual_fields = array_diff($fields, $group_by);   //actual columns which will be shown without group by fields
	$actual_columns_count = count($actual_fields);     //number of columns to be shown		

	$group_by_count = count($group_by);

	



?>


<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="apple-mobile-web-app-capable" content="yes" />
<title><?php  echo $title ?></title>

<link href="<?php 
/*
 if($print!= 0)

 {

	echo "print.css" ;

 }

 else

 {
*/
	echo $style_name . ".css" ;

 /*}*/

?>" rel="stylesheet" type="text/css" />




<link rel="apple-touch-icon" href="app-icon.png"/>
<link rel="apple-touch-icon-precomposed" href="app-icon.png" />
<link rel="apple-touch-startup-image" href="splash.png" />   
</head>

<body>
<div class="container">
<?php

if(empty ($_GET['print'])) //not in priting mode
{

	?>
<a class="toggleMenu" href="#">Menu</a>
<ul class="nav">
	<li  class="test">
		<a href="<?php echo $link_prev; ?>">Previous</a>
	</li>
	<li>
		<a href="<?php echo $link_next; ?>">Next</a>
	</li>
	<li>
		<a href="#">Print</a>
                    
                                                          
		<ul>
			<li>
				<a href="<?php echo $link_pdf_all; ?>">All Pages</a>
				<!--<ul>
					<li><a href="#">Trousers</a></li>
					<li><a href="#">Slacks</a></li>
					<li><a href="#">Jeans</a></li>
				</ul>-->
			</li>
			<li>
				<a href="<?php echo $link_pdf_current; ?>">Current Page</a>
				<!--<ul>
					<li><a href="#">Trousers</a></li>
					<li><a href="#">Slacks</a></li>
					<li><a href="#">Jeans</a></li>
					<li><a href="#">Leggings</a></li>
				</ul>-->
			</li>
		</ul>
	</li>
	<li>
		<a href="#">Export</a>
		<ul>
			<li>
				<a href="#">PDF</a>
				<ul>
					<li><a href="<?php echo $link_pdf_all; ?>">All Pages</a></li>
					<li><a href="<?php echo $link_pdf_current; ?>">Current Page</a></li>
				</ul>
			</li>
			<li>
				<a href="#">CSV</a>
				<ul>
					<li><a href="<?php echo $link_csv_all; ?>">All Pages</a></li>
					<li><a href="<?php echo $link_csv_current; ?>">Current Page</a></li>
				</ul>
			</li>
			<li>
				<a href="#">XML</a>
				<ul>
					<li><a href="<?php echo $link_xml_all; ?>">All Pages</a></li>
					<li><a href="<?php echo $link_xml_current; ?>">Current Page</a></li>
				</ul>
			</li>
		</ul>
	</li>
	<li>
		<a href="email_report.php">Send By Mail</a>

	</li>

</ul>
<div class="search-box">
    <form method="post" action="<?php echo $_SERVER['PHP_SELF']; ?>">  
    <input type="text" class="srch-txt" name="txtordnary_search" value="<?php echo get_default_value('txtordnary_search'); ?>" id="txtordnary_search"  />
    <div class="clear"></div>
    <input type="submit" class="srch-btn" name="btnordnary_search" value="Search" id="txtordnary_search"  />
    <br />
    
    <input type="submit" class="srch-btn" style="background-color: #8B8B8B; margin-top:5px;"  value="Show All" id="btnShowAll" name="btnShowAll" />
  <br />
</form>  
</div>
<?php } ?>
<?php if(trim($title) != ''){ ?>
<div class="report-name">Report Name : <?php echo $title ?></div>
 <?php } ?>
<!--<div class="group-row">Country:Egypt</div>
<div class="sub-row">City:Alexandria</div>-->
<?php 
    if(mysql_num_rows($result) == 0)
        echo '<div class="nav" style="padding: 8px;text-align: center;color: white;">No Data Found</div>';		

?>
<div class="grid">
    <table class="report-table">
        <?php
        
		while($row = mysql_fetch_array($result,MYSQL_ASSOC))

		{

			//fill array with current grouping fields
			foreach($group_by as $key=>$val)

			{
				$cur_group_ar[$val] = $row[$val] ;

			}					

			

			//print group by fields in case of grouping values variation
			if(count($last_group_ar)!=0)

			{

				$diff_index = grouping_diff_index($cur_group_ar,$last_group_ar);

			}

			else

			{

				$diff_index = 0 ;

			}



			if($diff_index !=-1)

			{
                                        if(count($group_by_source) > 0)
                                            echo '</table><br / >';
				for($i=$diff_index;$i<count($group_by_source);$i++) 

				{

					if($i ==0 && $diff_index==0)

						echo "<div class='group-row'>" .$labels[$group_by_source[$i]] .": " . $row[$group_by[$i] ] . " </div>";

					else

						echo "<div class='sub-row'>" .$labels[$group_by_source[$i]] .": " . $row[$group_by[$i] ] . "</div>";

				}
                                        if(count($group_by_source) > 0)
                                            echo '<table class="report-table">';

	     //echo"<tr><td height='15' $span class='TableHeader'></td></tr>";



				

		if($cur_row==0)		

		{

?>





	   <?php }

	 } ?> 



<?php 

			//print table columns

			if( ($group_by_count>0 && $diff_index !=-1) || $cur_row==0  ) //if there is a change in grouping

			{

				$i = 0;

				foreach($actual_fields_source as $key=>$val)
				{
                                    $temp = explode('.', $val);
                                    $field_ = (count($table) == 0)?$val:$temp[1];
                                        if(in_array($field_, $group_by))
                                             continue;
                                                     
					if($i==0) echo "<thead><tr>";
                                                  $mobile_hide = '';
                                                  if($i > 1 && $i < 5)
                                                      $mobile_hide = 'data-hide="phone"';
                                                  else if($i > 4)
                                                      $mobile_hide = 'data-hide="phone,tablet"';
                                                  if($i == 0)
                                                     $mobile_hide .= ' data-class="expand"';
					echo "<th $mobile_hide >$labels[$val]</th>";

					if($i == $actual_columns_count -1)  echo "</tr></thead>";

					$i++;

				}

			}



			

			//print row data

			echo "<tr>";

			foreach($actual_fields as $key=>$val)

			{
					if($toggle_row == 0)

						if(empty($row[$val]))

		        			echo "<td align='center' class='TableCell'>" . "&nbsp;" . "</td>";

						else

	        				echo "<td align='center' class='TableCell'>" . $row[$val] . "</td>";

					else

						if(empty($row[$val]))					

							echo "<td align='center' class='AlternateTableCell'>" . "&nbsp;"  ."</td>";					

						else

							echo "<td align='center' class='AlternateTableCell'>" . $row[$val] ."</td>";											

			}

			echo "</tr>";

			

			//change toggling of rows

		  	if($toggle_row == 0)

				$toggle_row = 1;

			else

				$toggle_row =0;

				

			//update new grouping

			if($diff_index !=-1)

			{

				$last_group_ar  =array();

				foreach($group_by as $key=>$val)

				{

					$last_group_ar[$val] = $row[$val] ;

				}

			}

			

			//increment current rows

			$cur_row ++;

		}

?>

    </table>
</div>
<div class="footer">Created by <a target="_blank" href="http://mysqlreports.com/">Smart Report Maker </a><br /> <!--a href="#">Go To Desktop Version</a--></div>
</div>

    <script type="text/javascript" src="../../Js/jquery-1.8.2.js"></script>
<script type="text/javascript" src="../../Js/footable-0.1.js"></script>
  <script type="text/javascript"> 
 
  
  
    $(function() {
        
      $('.report-table').footable();
      $("#btnShowAll").click(function(){ 
           $('#txtordnary_search').val('');
      });
      
     
        var $first = $('.report-table').eq(1);
      $('.report-table').each(function(index,tbl){
          $(tbl).children('thead').children('tr').children('th').each(function(index_th,cell){
              
              var width = $first.find('th').eq(index_th).width();
              $(cell).css('width',width+'px');
          });
      });
        
    });
	
	
	$(document).ready(function(){
 var datasource = <?php echo "'" . $datasource . "';" ; ?>
 if(datasource=='sql'){
 $("#txtordnary_search").hide();
  $(".srch-btn").hide();
  //$("#search_advanced").css('visibility','hidden');
 
  }
  
 
 }); 
  </script>
<script type="text/javascript" src="../../Js/script.js"></script>
</body>
</html>
