<?php
//sef,15-Apr-2014 20:43:28
$form_host='localhost';
$form_user='root';
$form_pass='';
$form_db='sniders2013';
$form_permission='010';
$form_desc=array(array('varchar(30)','2','','','','l-DESC','Array'),array('int(2)','0','PRI','','','l-VALUE','Array'));
$form_table='t-lookup';
$form_sql='';
$form_autodetect='';
$form_data_source='table';
$form_unique=array('l-VALUE');
$form_fields=array('l-VALUE','l-DESC');
$form_layout='Columner';
$form_style_name='blue';
$form_title='Billing Date Update';
$form_date_created='15-Apr-2014 20:41:07';
$form_form_desc='a';
$form_file_name='a';
$form_records_per_page='10';
$host='localhost';
$user='root';
$pass='';
$db='sniders2013';
$datasource='table';
$table=array('t-customer');
$tables_filters=array('`t-customer`.`C-CUSTNO` is = "00499"');
$fields=array('C-CUSTNO','C-NAME','C-ADDR1','C-ADDR2','C-CITY','C-STATE','C-ZIP','C-SADDR1','C-SADDR2','C-SCITY','C-SSTATE','C-SZIP','C-CONTACT','C-TITLE','C-PHONE','C-PHONE2','C-TERM','c-SHIP-METHOD','C-DEL-SURCHARGE','C-ROUTE','C-BILLING','C-BILLING-METH','C-PRICE','C-DISC-OUTFIT','C-DISCSHOE','C-DTADD','C-DTUPD','C-ACTIVE','C-DISCNT-PCT');
$fields2=array('C-CUSTNO','C-NAME','C-ADDR1','C-ADDR2','C-CITY','C-STATE','C-ZIP','C-SADDR1','C-SADDR2','C-SCITY','C-SSTATE','C-SZIP','C-CONTACT','C-TITLE','C-PHONE','C-PHONE2','C-TERM','c-SHIP-METHOD','C-DEL-SURCHARGE','C-ROUTE','C-BILLING','C-BILLING-METH','C-PRICE','C-DISC-OUTFIT','C-DISCSHOE','C-DTADD','C-DTUPD','C-ACTIVE','C-DISCNT-PCT');
$labels=$labels = 'a:29:{s:8:"C-CUSTNO";s:8:"C-CUSTNO";s:6:"C-NAME";s:6:"C-NAME";s:7:"C-ADDR1";s:7:"C-ADDR1";s:7:"C-ADDR2";s:7:"C-ADDR2";s:6:"C-CITY";s:6:"C-CITY";s:7:"C-STATE";s:7:"C-STATE";s:5:"C-ZIP";s:5:"C-ZIP";s:8:"C-SADDR1";s:8:"C-SADDR1";s:8:"C-SADDR2";s:8:"C-SADDR2";s:7:"C-SCITY";s:7:"C-SCITY";s:8:"C-SSTATE";s:8:"C-SSTATE";s:6:"C-SZIP";s:6:"C-SZIP";s:9:"C-CONTACT";s:9:"C-CONTACT";s:7:"C-TITLE";s:7:"C-TITLE";s:7:"C-PHONE";s:7:"C-PHONE";s:8:"C-PHONE2";s:8:"C-PHONE2";s:6:"C-TERM";s:6:"C-TERM";s:13:"c-SHIP-METHOD";s:13:"c-SHIP-METHOD";s:15:"C-DEL-SURCHARGE";s:15:"C-DEL-SURCHARGE";s:7:"C-ROUTE";s:7:"C-ROUTE";s:9:"C-BILLING";s:9:"C-BILLING";s:14:"C-BILLING-METH";s:14:"C-BILLING-METH";s:7:"C-PRICE";s:7:"C-PRICE";s:13:"C-DISC-OUTFIT";s:13:"C-DISC-OUTFIT";s:10:"C-DISCSHOE";s:10:"C-DISCSHOE";s:7:"C-DTADD";s:7:"C-DTADD";s:7:"C-DTUPD";s:7:"C-DTUPD";s:8:"C-ACTIVE";s:8:"C-ACTIVE";s:12:"C-DISCNT-PCT";s:12:"C-DISCNT-PCT";}';;
$group_by=array();
$sort_by=array();
$layout='AlignLeft2';
$style_name='GreyScale';
$Forget_password='';
$security='';
$members='';
$sec_Username='';
$sec_pass='';
$sec_table='';
$sec_Username_Field='';
$sec_pass_Field='';
$sec_email='';
$sec_email_field='';
$title='sef';
$date_created='15-Apr-2014 20:43:28';
$header='feefw';
$footer='efwfew';
$file_name='ewefw';
$records_per_page='10';
$chkSearch='Yes';
$is_mobile='';
?>